name: Run test and lint

on:
  push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2
      - uses: actions/setup-node@v4
      
      - name: Build container 
        run: |
          docker compose up -d

      - name: Run npm ci
        run: |
          docker compose exec --user root app npm ci
      
      - name: Run npm run lint
        run: |
          docker compose exec app npm run lint

      - name: Run npm run jest
        run: |
          docker compose exec app npm run test
        